In [1]:
# step 1 (Already installed !pip install numpy)

In [12]:
import numpy as np

In [13]:
# step2

In [14]:
l1 = [21,51,32,87,45,68,12]
l2 = [2.5,3.9,4.7,9.4,22.4,8.7,29.1]
l3 = [2+6j, 54-15j, 21+2j, 7-77j]


In [15]:
p = np.array(l1)
p

array([21, 51, 32, 87, 45, 68, 12])

In [16]:
p.ndim

1

In [17]:
q = np.array(l2)
q

array([ 2.5,  3.9,  4.7,  9.4, 22.4,  8.7, 29.1])

In [18]:
q.ndim

1

In [19]:
r = np.array(l3)
r

array([ 2. +6.j, 54.-15.j, 21. +2.j,  7.-77.j])

In [20]:
r.ndim

1

In [21]:
a = np.array([[3,8],
             [4,9],
             [2,7]])
b = np.array([[2,5],
             [1,7],
             [6,8]])

In [22]:
a+b                     #add

array([[ 5, 13],
       [ 5, 16],
       [ 8, 15]])

In [23]:
a-b                    #subtract

array([[ 1,  3],
       [ 3,  2],
       [-4, -1]])

In [24]:
np.add(a,b)            #add

array([[ 5, 13],
       [ 5, 16],
       [ 8, 15]])

In [25]:
np.subtract(a,b)       #subtract

array([[ 1,  3],
       [ 3,  2],
       [-4, -1]])

In [26]:
np.transpose(a)       #transpose

array([[3, 4, 2],
       [8, 9, 7]])

In [27]:
b.transpose()         #transpose

array([[2, 1, 6],
       [5, 7, 8]])

In [28]:
a.dot(b.transpose())   #dot product

array([[46, 59, 82],
       [53, 67, 96],
       [39, 51, 68]])

In [29]:
np.dot(a.transpose(),b) #dot product

array([[ 22,  59],
       [ 67, 159]])

In [30]:
a*b                     #element wise product

array([[ 6, 40],
       [ 4, 63],
       [12, 56]])

In [31]:
#accesing elements
print( a[1, 1] )       #2nd row 2nd column
print( b[2, 0] )       #3rd row 1st column

9
6


In [32]:
print(a[:,1])         #2nd column
print(b[2,:])         #3rd row

[8 9 7]
[6 8]


In [33]:
c = l1[:]
c

[21, 51, 32, 87, 45, 68, 12]

In [34]:
c[1:5]               #slicing of list

[51, 32, 87, 45]

In [35]:
c[::-1]              #reverse

[12, 68, 45, 87, 32, 51, 21]

In [36]:
c.reverse()         #reverse
c

[12, 68, 45, 87, 32, 51, 21]

In [1]:
import requests

In [3]:
url = "https://www.stats.govt.nz/assets/Uploads/Employment-indicators/Employment-indicators-June-2020/Download-data/employment-indicators-june-2020-regional-filled-jobs.csv"

In [6]:
file = requests.get(url)

In [64]:
new_file = open("data_w1.csv",'wb')
new_file.write(file.content)
new_file.close()

In [70]:
np.genfromtxt("data_w1.csv", dtype = None, delimiter = ",", encoding = "utf-8")

array([['Region', 'Period', 'Value', ..., 'Units', 'Magnitude',
        'Series_title_1'],
       ['Auckland Region', '2019.05', '721535', ..., 'Number ', '0',
        'Actual'],
       ['Auckland Region', '2019.06', '723158', ..., 'Number ', '0',
        'Actual'],
       ...,
       ['West Coast Region', '2020.04', '16244', ..., 'Number ', '0',
        'Actual'],
       ['West Coast Region', '2020.05', '16255', ..., 'Number ', '0',
        'Actual'],
       ['West Coast Region', '2020.06', '16187', ..., 'Number ', '0',
        'Actual']], dtype='<U25')

In [72]:
help(np.loadtxt)

Help on function loadtxt in module numpy.lib.npyio:

loadtxt(fname, dtype=<class 'float'>, comments='#', delimiter=None, converters=None, skiprows=0, usecols=None, unpack=False, ndmin=0, encoding='bytes')
    Load data from a text file.
    
    Each row in the text file must have the same number of values.
    
    Parameters
    ----------
    fname : file, str, or pathlib.Path
        File, filename, or generator to read.  If the filename extension is
        ``.gz`` or ``.bz2``, the file is first decompressed. Note that
        generators should return byte strings for Python 3k.
    dtype : data-type, optional
        Data-type of the resulting array; default: float.  If this is a
        structured data-type, the resulting array will be 1-dimensional, and
        each row will be interpreted as an element of the array.  In this
        case, the number of columns used must match the number of fields in
        the data-type.
    comments : str or sequence of str, optional
       